---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/time/docker/radarr/data:/config
      - /home/time/docker/radarr/movies:/movies #optional
      - /home/time/docker/radarr/downloadclient-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped